version: "2"
services:
  db:
    image: mysql:8.0
    volumes:
      - "./.db:/var/lib/mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: memo
      MYSQL_USER: oscar
      MYSQL_PASSWORD: oscar
